# Generated by Django 6.0.1 on 2026-04-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="can_manage_payments",
            field=models.BooleanField(
                default=False, help_text="Can view and manage payment transactions"
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="can_manage_services",
            field=models.BooleanField(
                default=False, help_text="Can manage service categories and listings"
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="can_manage_users",
            field=models.BooleanField(
                default=False, help_text="Can manage (create, update, delete) users"
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="can_view_analytics",
            field=models.BooleanField(
                default=False, help_text="Can view platform analytics and reports"
            ),
        ),
    ]
