# Generated by Django 6.0.1 on 2026-01-30 12:44

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('address', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('can_manage_users', models.BooleanField(default=True, help_text='Can manage (create, update, delete) users')),
                ('can_manage_services', models.BooleanField(default=True, help_text='Can manage service categories and listings')),
                ('can_manage_payments', models.BooleanField(default=True, help_text='Can view and manage payment transactions')),
                ('can_view_analytics', models.BooleanField(default=True, help_text='Can view platform analytics and reports')),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
                'db_table': 'admins',
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('id_document', models.FileField(blank=True, help_text='Upload ID document for verification', null=True, upload_to='provider_documents/')),
                ('certification', models.FileField(blank=True, help_text='Upload professional certifications', null=True, upload_to='provider_certifications/')),
                ('business_name', models.CharField(blank=True, help_text='Business or company name', max_length=100, null=True)),
                ('bio', models.TextField(blank=True, help_text='Brief description about services', null=True)),
                ('years_of_experience', models.IntegerField(default=0, help_text='Years of professional experience')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate in USD', max_digits=10, null=True)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, help_text='Total earnings from all jobs', max_digits=10)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Balance available for withdrawal', max_digits=10)),
                ('is_available', models.BooleanField(default=True, help_text='Is the provider currently available for jobs?')),
                ('service_radius', models.IntegerField(default=10, help_text='Service radius in kilometers')),
                ('total_jobs', models.IntegerField(default=0, help_text='Total number of jobs received')),
                ('completed_jobs', models.IntegerField(default=0, help_text='Total number of completed jobs')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating from reviews', max_digits=3)),
                ('total_reviews', models.IntegerField(default=0, help_text='Total number of reviews received')),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
                'db_table': 'providers',
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Current wallet balance', max_digits=10)),
                ('total_cashback', models.DecimalField(decimal_places=2, default=0.0, help_text='Total cashback earned', max_digits=10)),
                ('total_bookings', models.IntegerField(default=0, help_text='Total number of bookings made')),
                ('favorite_providers', models.ManyToManyField(blank=True, related_name='favorited_by', to='users.provider')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
            },
            bases=('users.user',),
        ),
    ]
