services:
  db:
    image: postgis/postgis:17-3.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: snapfix_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    build: .
    command: sh -c "until python manage.py migrate --noinput; do echo 'Waiting for DB...'; sleep 2; done && python manage.py create_superuser && gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 2 --timeout 120 --reload --reload-engine poll"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - media_files:/app/media
      - log_files:/app/logs
      - ./secrets:/app/secrets:ro
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/secrets/firebase-service-account.json
    env_file: .env
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A config worker --loglevel=info --concurrency=2
    volumes:
      - .:/app
      - ./secrets:/app/secrets:ro
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/secrets/firebase-service-account.json
    env_file: .env
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  redis_data:
  media_files:
  log_files:
