services:
  db:
    image: postgis/postgis:17-3.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: snapfix_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  web:
    build: .
    command: sh -c "until python manage.py migrate --noinput; do echo 'Waiting for DB...'; sleep 2; done && python manage.py create_superuser && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - media_files:/app/media
      - log_files:/app/logs
    env_file: .env
    depends_on:
      - db

volumes:
  postgres_data:
  media_files:
  log_files:
