# Generated by Django 6.0.1 on 2026-03-22 21:05

import uuid

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Office",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "address",
                    models.CharField(help_text="Full string address", max_length=500),
                ),
                (
                    "landmark",
                    models.CharField(
                        blank=True,
                        help_text="Nearby famous place e.g. 'Next to Cairo Tower'",
                        max_length=200,
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        geography=True,
                        help_text="Exact coordinates (longitude, latitude)",
                        null=True,
                        srid=4326,
                    ),
                ),
                (
                    "working_hours",
                    models.CharField(
                        help_text="e.g. 'Sun–Thu 9:00 AM – 5:00 PM'", max_length=200
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offices",
                        to="core.region",
                    ),
                ),
            ],
            options={
                "verbose_name": "Office",
                "verbose_name_plural": "Offices",
                "db_table": "offices",
                "ordering": ["region", "name"],
            },
        ),
    ]
