# Generated by Django 6.0.1 on 2026-03-07 16:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='region',
            name='longitude',
        ),
        migrations.AddField(
            model_name='region',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Region center point (longitude, latitude)', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji icon e.g. 🔧', max_length=10),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['is_active'], name='regions_is_acti_dadff5_idx'),
        ),
    ]
