# Generated by Django 6.0.1 on 2026-04-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_office"),
    ]

    operations = [
        migrations.AlterField(
            model_name="office",
            name="working_hours",
            field=models.CharField(
                help_text="e.g. 'Sun-Thu 9:00 AM - 5:00 PM'", max_length=200
            ),
        ),
    ]
