# Generated by Django 6.0.1 on 2026-02-03 17:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('id_document', models.FileField(blank=True, help_text='ID document for verification', null=True, upload_to='provider_documents/')),
                ('certification', models.FileField(blank=True, help_text='Professional certifications', null=True, upload_to='provider_certifications/')),
                ('business_name', models.CharField(blank=True, help_text='Business or company name', max_length=100)),
                ('bio', models.TextField(blank=True, help_text='Brief description about services')),
                ('years_of_experience', models.IntegerField(default=0, help_text='Years of professional experience', validators=[django.core.validators.MinValueValidator(0)])),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate in USD', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, help_text='Total earnings from all jobs', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('available_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Balance available for withdrawal', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_available', models.BooleanField(default=True, help_text='Currently available for jobs')),
                ('service_radius', models.IntegerField(default=10, help_text='Service radius in kilometers', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_jobs', models.IntegerField(default=0, help_text='Total number of jobs received', validators=[django.core.validators.MinValueValidator(0)])),
                ('completed_jobs', models.IntegerField(default=0, help_text='Total number of completed jobs', validators=[django.core.validators.MinValueValidator(0)])),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating from reviews', max_digits=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_reviews', models.IntegerField(default=0, help_text='Total number of reviews received', validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
                'db_table': 'providers',
                'indexes': [models.Index(fields=['verification_status'], name='providers_verific_9bf07a_idx'), models.Index(fields=['is_available'], name='providers_is_avai_b2218e_idx')],
            },
            bases=('user.user',),
        ),
    ]
