# Generated by Django 6.0.1 on 2026-04-09 19:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('staff', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=8)),
                ('business_name', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('years_of_experience', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('available_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_available', models.BooleanField(default=True)),
                ('service_radius', models.IntegerField(default=10, help_text='Service radius in kilometers', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_jobs', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('completed_jobs', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('average_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_reviews', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('categories', models.ManyToManyField(blank=True, related_name='providers', to='core.category')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='providers', to='core.region')),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
                'db_table': 'providers',
            },
            bases=('user.user',),
        ),
        migrations.CreateModel(
            name='ProviderOnboarding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Must be a valid Egyptian mobile number (e.g., 01012345678 or +201012345678).', regex='^(\\+?20)?01[0125]\\d{8}$')])),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('years_of_experience', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('bio', models.TextField(blank=True)),
                ('nid_front', models.ImageField(upload_to='onboarding/nid/front/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])])),
                ('nid_back', models.ImageField(upload_to='onboarding/nid/back/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])])),
                ('police_clearance_certificate', models.FileField(upload_to='onboarding/pcc/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])])),
                ('professional_certificate', models.FileField(blank=True, null=True, upload_to='onboarding/certificates/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])])),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='onboarding/photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('changes_required', 'Changes Required'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16)),
                ('admin_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('change_requests', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_application', to='provider.provider')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_applications', to='core.category')),
                ('provider', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_application', to='provider.provider')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_applications', to='core.region')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_onboardings', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Provider Onboarding Application',
                'verbose_name_plural': 'Provider Onboarding Applications',
                'db_table': 'provider_onboarding',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['verification_status'], name='providers_verific_9bf07a_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['is_available'], name='providers_is_avai_b2218e_idx'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['region', 'is_available'], name='providers_region__fb779d_idx'),
        ),
        migrations.AddIndex(
            model_name='provideronboarding',
            index=models.Index(fields=['status', '-submitted_at'], name='provider_on_status_5d5ba8_idx'),
        ),
        migrations.AddIndex(
            model_name='provideronboarding',
            index=models.Index(fields=['email'], name='provider_on_email_a2d84d_idx'),
        ),
        migrations.AddIndex(
            model_name='provideronboarding',
            index=models.Index(fields=['region', 'category', 'status'], name='provider_on_region__12b5e4_idx'),
        ),
    ]
