# Generated by Django 6.0.1 on 2026-02-14 16:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('provider', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Service categories this provider operates in', related_name='providers', to='core.category'),
        ),
        migrations.AddField(
            model_name='provider',
            name='region',
            field=models.ForeignKey(blank=True, help_text='Primary region where provider operates', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='providers', to='core.region'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='provider',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=8),
        ),
        migrations.CreateModel(
            name='ProviderOnboarding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(help_text='Date of birth')),
                ('age', models.IntegerField(help_text='Must be 18 or older', validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)])),
                ('address', models.TextField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Initial hourly rate', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('years_of_experience', models.IntegerField(default=0, help_text='Years of experience in this field', validators=[django.core.validators.MinValueValidator(0)])),
                ('bio', models.TextField(blank=True, help_text='Brief description of services and experience')),
                ('nid_front', models.ImageField(help_text='National ID - Front side', upload_to='onboarding/nid/front/')),
                ('nid_back', models.ImageField(help_text='National ID - Back side', upload_to='onboarding/nid/back/')),
                ('police_clearance_certificate', models.FileField(help_text='Police Clearance Certificate (PCC)', upload_to='onboarding/pcc/')),
                ('professional_certificate', models.FileField(blank=True, help_text='Professional certificates (optional)', null=True, upload_to='onboarding/certificates/')),
                ('profile_photo', models.ImageField(blank=True, help_text='Profile photo', null=True, upload_to='onboarding/photos/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('changes_required', 'Changes Required'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes from admin')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection')),
                ('change_requests', models.TextField(blank=True, help_text='Specific changes requested')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Service category', on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_applications', to='core.category')),
                ('provider', models.OneToOneField(blank=True, help_text='Provider account created after approval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_application', to='provider.provider')),
                ('region', models.ForeignKey(help_text='Region where provider will operate', on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_applications', to='core.region')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_onboardings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Provider Onboarding Application',
                'verbose_name_plural': 'Provider Onboarding Applications',
                'db_table': 'provider_onboarding',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['status', '-submitted_at'], name='provider_on_status_5d5ba8_idx'), models.Index(fields=['email'], name='provider_on_email_a2d84d_idx')],
            },
        ),
    ]
