# Generated by Django 6.0.1 on 2026-02-16 21:01

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('provider', '0002_provider_categories_provider_region_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provideronboarding',
            name='age',
        ),
        migrations.AlterField(
            model_name='provider',
            name='certification',
            field=models.FileField(blank=True, help_text='Professional certifications (Max 5MB)', null=True, upload_to='provider_certifications/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='provider',
            name='id_document',
            field=models.FileField(blank=True, help_text='ID document for verification (Max 5MB)', null=True, upload_to='provider_documents/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='provideronboarding',
            name='nid_back',
            field=models.ImageField(help_text='National ID - Back side (Max 5MB)', upload_to='onboarding/nid/back/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='provideronboarding',
            name='nid_front',
            field=models.ImageField(help_text='National ID - Front side (Max 5MB)', upload_to='onboarding/nid/front/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='provideronboarding',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid Egyptian mobile number (e.g., 010XXXXXXXX or +2010XXXXXXXX).', regex='^(?:\\+20|20)?1[0125]\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='provideronboarding',
            name='police_clearance_certificate',
            field=models.FileField(help_text='Police Clearance Certificate (Max 5MB)', upload_to='onboarding/pcc/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='provideronboarding',
            name='professional_certificate',
            field=models.FileField(blank=True, help_text='Professional certificates - optional (Max 5MB)', null=True, upload_to='onboarding/certificates/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='provideronboarding',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Profile photo - optional (Max 5MB)', null=True, upload_to='onboarding/photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['region', 'is_available'], name='providers_region__fb779d_idx'),
        ),
        migrations.AddIndex(
            model_name='provideronboarding',
            index=models.Index(fields=['region', 'category', 'status'], name='provider_on_region__12b5e4_idx'),
        ),
    ]
