# Generated by Django 6.0.1 on 2026-02-19 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_remove_provideronboarding_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provideronboarding',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid Egyptian mobile number (e.g., 01012345678 or +201012345678).', regex='^(\\+?20)?01[0125]\\d{8}$')]),
        ),
    ]
