# Generated by Django 6.0.1 on 2026-05-01 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("provider", "0003_aivalidationlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="declined_jobs",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
