# Generated by Django 6.0.1 on 2026-02-19 20:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('provider', '0004_alter_provideronboarding_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='provider',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='provider',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='business_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='provider',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='providers', to='core.category'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='completed_jobs',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='provider',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='provider',
            name='id_document',
            field=models.FileField(blank=True, help_text='ID document (Max 5MB)', null=True, upload_to='provider_documents/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='provider',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='providers', to='core.region'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='provider',
            name='total_jobs',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='provider',
            name='total_reviews',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='provider',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='provider',
            name='years_of_experience',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='provideronboarding',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='provideronboarding',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='provideronboarding',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_applications', to='core.category'),
        ),
        migrations.AlterField(
            model_name='provideronboarding',
            name='change_requests',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='provideronboarding',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='provideronboarding',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='provideronboarding',
            name='nid_back',
            field=models.ImageField(upload_to='onboarding/nid/back/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='provideronboarding',
            name='nid_front',
            field=models.ImageField(upload_to='onboarding/nid/front/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='provideronboarding',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Must be a valid Egyptian mobile number (e.g., 01012345678 or +201012345678).', regex='^(\\+?20)?01[0125]\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='provideronboarding',
            name='police_clearance_certificate',
            field=models.FileField(upload_to='onboarding/pcc/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='provideronboarding',
            name='professional_certificate',
            field=models.FileField(blank=True, null=True, upload_to='onboarding/certificates/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='provideronboarding',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='onboarding/photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='provideronboarding',
            name='provider',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_application', to='provider.provider'),
        ),
        migrations.AlterField(
            model_name='provideronboarding',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_applications', to='core.region'),
        ),
        migrations.AlterField(
            model_name='provideronboarding',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='provideronboarding',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_onboardings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='provideronboarding',
            name='years_of_experience',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
