# Generated by Django 6.0.1 on 2026-03-06 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0005_alter_provider_available_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='certification',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='id_document',
        ),
    ]
