# Generated by Django 6.0.1 on 2026-03-07 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0006_remove_provider_certification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provideronboarding',
            name='applicant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_application', to='provider.provider'),
        ),
    ]
