# Generated by Django 6.0.1 on 2026-03-13 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0007_provideronboarding_applicant'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provideronboarding',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_onboardings', to='staff.staff'),
        ),
    ]
