# Generated by Django 6.0.1 on 2026-03-13 15:25

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("address", models.TextField(help_text="Exact service address")),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "is_urgent",
                    models.BooleanField(
                        default=False, help_text="Customer flagged this as urgent"
                    ),
                ),
                ("preferred_date", models.DateField()),
                ("preferred_time", models.TimeField()),
                (
                    "estimated_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price estimated at booking time",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Actual price after job completion",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("assigned", "Assigned"),
                            ("confirmed", "Confirmed"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("declined", "Declined"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "cancelled_by",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("customer", "Customer"),
                            ("provider", "Provider"),
                            ("admin", "Admin"),
                        ],
                        max_length=10,
                    ),
                ),
                ("cancellation_reason", models.TextField(blank=True)),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes (not visible to customer/provider)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_requests",
                        to="core.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Request",
                "verbose_name_plural": "Service Requests",
                "db_table": "service_requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
