# Generated by Django 6.0.1 on 2026-04-09 19:51

import django.contrib.gis.db.models.fields
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(help_text='1-5 stars', validators=[django.core.validators.MinValueValidator(1)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'db_table': 'reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.TextField(help_text='Exact service address')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Exact pin-drop location (longitude, latitude)', srid=4326)),
                ('floor_number', models.CharField(help_text='Floor number (e.g. 3, Ground, Basement)', max_length=20)),
                ('apartment_number', models.CharField(help_text='Apartment or unit number', max_length=20)),
                ('special_mark', models.TextField(help_text='Landmark or navigation instructions for the provider')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_urgent', models.BooleanField(default=False, help_text='Customer flagged this as urgent')),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, help_text="Customer's rough estimate at booking time (informational only)", max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price submitted by the provider', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, help_text='Locked from quoted_price when customer approves. This is the single authoritative amount due.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card (Stripe)'), ('wallet', 'Wallet')], default='cash', help_text='How the non-wallet portion is paid. WALLET = full amount from wallet; CASH = remainder collected by provider; CARD = remainder charged via Stripe.', max_length=6)),
                ('wallet_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount the customer pre-commits to pay from their wallet. Must be ≤ final_price. Can be 0 (no wallet used).', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], db_index=True, default='pending', max_length=7)),
                ('stripe_payment_intent_id', models.CharField(blank=True, help_text='Stripe PaymentIntent ID for card payments', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('quoted', 'Quoted'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=11)),
                ('cancelled_by', models.CharField(blank=True, choices=[('customer', 'Customer'), ('provider', 'Provider'), ('admin', 'Admin')], max_length=8)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('decline_reason', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Service Request',
                'verbose_name_plural': 'Service Requests',
                'db_table': 'service_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='service_requests/photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'service_request_photos',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
