# Generated by Django 6.0.1 on 2026-02-19 17:55

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('customer', '0002_initial'),
        ('provider', '0004_alter_provideronboarding_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.TextField(help_text='Exact service address')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_urgent', models.BooleanField(default=False, help_text='Customer flagged this as urgent')),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price estimated at booking time', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, help_text='Actual price after job completion', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('cancelled_by', models.CharField(blank=True, choices=[('customer', 'Customer'), ('provider', 'Provider'), ('admin', 'Admin')], max_length=10, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes from admin (not visible to customer/provider)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='core.category')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='customer.customer')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='provider.provider')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='core.region')),
            ],
            options={
                'verbose_name': 'Service Request',
                'verbose_name_plural': 'Service Requests',
                'db_table': 'service_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='service_req_status_af917d_idx'), models.Index(fields=['customer', 'status'], name='service_req_custome_7d484f_idx'), models.Index(fields=['provider', 'status'], name='service_req_provide_b3bb72_idx'), models.Index(fields=['region', 'category', 'status'], name='service_req_region__f99915_idx'), models.Index(fields=['preferred_date', 'status'], name='service_req_preferr_7c7e3e_idx')],
            },
        ),
    ]
