# Generated by Django 6.0.1 on 2026-02-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes (not visible to customer/provider)'),
        ),
    ]
