# Generated by Django 6.0.1 on 2026-05-01 16:21

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="booking_mode",
            field=models.CharField(
                choices=[
                    ("broadcast", "Broadcast to All Providers"),
                    ("direct", "Direct (Favorites)"),
                    ("recommended", "AI Recommended"),
                ],
                db_index=True,
                default="broadcast",
                max_length=11,
            ),
        ),
        migrations.CreateModel(
            name="AIRecommendationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "triggered_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("category_name", models.CharField(blank=True, max_length=200)),
                ("is_urgent", models.BooleanField(default=False)),
                (
                    "candidate_snapshot",
                    models.JSONField(
                        default=list,
                        help_text="List of scored candidate dicts (provider id, score, signals) captured at call time.",
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("fallback", "Fallback (generic reasons)"),
                            ("bypassed", "Bypassed (flag off)"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "raw_response",
                    models.TextField(
                        blank=True,
                        help_text="Raw text returned by the AI before JSON parsing.",
                    ),
                ),
                (
                    "parsed_reasons",
                    models.JSONField(
                        default=dict,
                        help_text="Parsed {provider_id: reason} map returned to the caller.",
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("model_id", models.CharField(blank=True, max_length=100)),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                (
                    "service_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_recommendation_logs",
                        to="booking.servicerequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Recommendation Log",
                "verbose_name_plural": "AI Recommendation Logs",
                "db_table": "ai_recommendation_logs",
                "ordering": ["-triggered_at"],
            },
        ),
    ]
