# Generated by Django 6.0.1 on 2026-03-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="decline_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="declined_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="cancelled_by",
            field=models.CharField(
                blank=True,
                choices=[
                    ("customer", "Customer"),
                    ("provider", "Provider"),
                    ("admin", "Admin"),
                ],
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("assigned", "Assigned"),
                    ("confirmed", "Confirmed"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("declined", "Declined"),
                ],
                db_index=True,
                default="pending",
                max_length=11,
            ),
        ),
    ]
