# Generated by Django 6.0.1 on 2026-05-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0003_servicerequest_booking_mode_airecommendationlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airecommendationlog",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("success", "Success"),
                    ("fallback", "Fallback (generic reasons)"),
                    ("bypassed", "Bypassed (flag off)"),
                    ("error", "Error"),
                ],
                db_index=True,
                max_length=8,
            ),
        ),
    ]
