# Generated by Django 6.0.1 on 2026-04-02 22:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0004_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicerequest",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="servicerequest",
            name="longitude",
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="apartment_number",
            field=models.CharField(
                blank=True, help_text="Apartment or unit number", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="floor_number",
            field=models.CharField(
                blank=True,
                help_text="Floor number (e.g. 3, Ground, Basement)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                geography=True,
                help_text="Exact pin-drop location (longitude, latitude)",
                null=True,
                srid=4326,
            ),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="special_mark",
            field=models.TextField(
                blank=True,
                help_text="Landmark or navigation instructions for the provider",
            ),
        ),
    ]
