# Generated by Django 6.0.1 on 2026-04-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0006_require_location_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("assigned", "Assigned"),
                    ("confirmed", "Confirmed"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="pending",
                max_length=11,
            ),
        ),
    ]
