# Generated by Django 6.0.1 on 2026-04-09 13:37

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0007_alter_servicerequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("card", "Card (Stripe)"),
                    ("wallet", "Wallet"),
                ],
                default="cash",
                help_text="How the non-wallet portion is paid. WALLET = full amount from wallet; CASH = remainder collected by provider; CARD = remainder charged via Stripe.",
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="quoted_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Price submitted by the provider",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="stripe_payment_intent_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe PaymentIntent ID for card payments",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="wallet_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Amount the customer pre-commits to pay from their wallet. Must be ≤ final_price. Can be 0 (no wallet used).",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="admin_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="estimated_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Customer's rough estimate at booking time (informational only)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="final_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Locked from quoted_price when customer approves. This is the single authoritative amount due.",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("assigned", "Assigned"),
                    ("quoted", "Quoted"),
                    ("confirmed", "Confirmed"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="pending",
                max_length=11,
            ),
        ),
        migrations.CreateModel(
            name="ServiceRequestPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="service_requests/photos/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "service_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="booking.servicerequest",
                    ),
                ),
            ],
            options={
                "db_table": "service_request_photos",
                "ordering": ["uploaded_at"],
            },
        ),
    ]
