"""
Provider Onboarding – Comprehensive Unit Tests
================================================
Run with:
    python manage.py test apps.provider.tests.test_provider_onboarding -v 2

Suites
------
1. ProviderModelTests               – Provider model methods
2. ProviderOnboardingModelTests     – FSM transitions and guards
3. ProviderOnboardingAdminFormTests – Admin form validation
4. OnboardingEdgeCaseTests          – Happy paths and edge cases
5. ProviderAPITests                 – Register / login / profile endpoints
6. RegressionTests                  – One test per bug fix; must stay green forever

Output
------
Test progress is written to the standard test logger at DEBUG level.
To see it while running:
    python manage.py test ... --verbosity 2
Or configure LOGGING in settings to enable the "provider.tests" logger.

Ruff compliance
---------------
T201 – print() replaced with logger.debug() throughout.
S106 – hardcoded test passwords are accepted in test files; add
       # noqa: S106  on each line or suppress the rule for the tests
       directory in ruff.toml: [tool.ruff.lint.per-file-ignores]
       "apps/*/tests/**" = ["S106"]
N806 – get_user_model() result stored as `user_model` (lowercase).
F841 – unused `reviewer` variable removed from regression test.
"""

from __future__ import annotations

import logging
import uuid
from datetime import date, timedelta
from decimal import Decimal
from io import BytesIO

from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.core.files.uploadedfile import SimpleUploadedFile
from django.test import TestCase
from django.utils import timezone

log = logging.getLogger("provider.tests")

# ── Output helpers ─────────────────────────────────────────────────────────────
# All output goes through the standard logging framework so it respects the
# project's log level configuration and does not trigger ruff T201.

_SEP = "─" * 70


def _section(title: str) -> None:
    log.debug("\n%s\n  %s\n%s", _SEP, title, _SEP)


def _step(msg: str) -> None:
    log.debug("  ▶ %s", msg)


def _ok(msg: str) -> None:
    log.debug("  ✅ %s", msg)


def _show(label: str, value: object) -> None:
    log.debug("  %-35s %r", label, value)


# ── Image fixture ──────────────────────────────────────────────────────────────


def small_image(name: str = "test.png") -> SimpleUploadedFile:
    """
    Return a real 1×1 white PNG generated by Pillow.

    Django's ImageField runs PIL.Image.open() + image.verify() on every upload.
    Hand-crafted byte strings fail verify() because they lack valid scan data.
    Pillow.Image.save() always produces a fully valid file — the only approach
    that works reliably at the form-validation layer.
    PNG is preferred over JPEG: it is lossless, deterministic, and requires no
    quality/compression parameters.
    """
    from PIL import Image

    buf = BytesIO()
    Image.new("RGB", (1, 1), color=(255, 255, 255)).save(buf, format="PNG")
    buf.seek(0)
    return SimpleUploadedFile(name, buf.read(), content_type="image/png")


# ── Fixture factories ──────────────────────────────────────────────────────────


def make_region():
    from apps.core.models import Region

    return Region.objects.create(
        name=f"Region {uuid.uuid4().hex[:6]}",
        slug=f"region-{uuid.uuid4().hex[:6]}",
        code=f"RGN{uuid.uuid4().hex[:3].upper()}",
    )


def make_category():
    from apps.core.models import Category

    return Category.objects.create(
        name=f"Category {uuid.uuid4().hex[:6]}",
        slug=f"category-{uuid.uuid4().hex[:6]}",
    )


def make_staff():
    from apps.staff.models import Staff

    uid = uuid.uuid4().hex[:6]
    return Staff.objects.create_user(  # noqa: S106
        email=f"staff_{uid}@test.com",
        password="staff1234",  # noqa: S106
        first_name="Staff",
        last_name="User",
    )


def make_provider(
    email: str | None = None, active: bool = False, verified: bool = False
):
    from apps.provider.choices import ProviderVerificationStatus
    from apps.provider.models import Provider

    uid = uuid.uuid4().hex[:6]
    email = email or f"provider_{uid}@test.com"
    vstatus = (
        ProviderVerificationStatus.VERIFIED
        if verified
        else ProviderVerificationStatus.PENDING
    )
    p = Provider.objects.create_user(  # noqa: S106
        email=email,
        password="pass1234!!",  # noqa: S106
        first_name="John",
        last_name="Doe",
        is_active=active,
        verification_status=vstatus,
    )
    _step(f"Created Provider: email={email} active={active} vstatus={vstatus}")
    return p


def make_onboarding(region, category, applicant=None, email: str | None = None):
    from apps.provider.models import ProviderOnboarding

    uid = uuid.uuid4().hex[:6]
    email = email or (applicant.email if applicant else f"walkin_{uid}@test.com")
    dob = date.today() - timedelta(days=365 * 25)  # 25 years old
    obj = ProviderOnboarding(
        first_name="Jane",
        last_name="Walk-In",
        email=email,
        phone="01012345678",
        date_of_birth=dob,
        address="123 Cairo St",
        region=region,
        category=category,
        hourly_rate=Decimal("150.00"),
        years_of_experience=3,
        nid_front=small_image(),
        nid_back=small_image(),
        police_clearance_certificate=small_image(),
    )
    if applicant:
        obj.applicant = applicant
    obj.save()
    _step(f"Created ProviderOnboarding: email={email} status={obj.status}")
    return obj


# ═════════════════════════════════════════════════════════════════════════════
# 1.  Provider Model Tests
# ═════════════════════════════════════════════════════════════════════════════


class ProviderModelTests(TestCase):
    def setUp(self) -> None:
        self.region = make_region()
        self.category = make_category()

    def test_register_creates_inactive_pending_provider(self) -> None:
        _section("1.1 – API registration → inactive + pending provider")
        from apps.provider.choices import ProviderVerificationStatus

        provider = make_provider(email="new_reg@test.com", active=False, verified=False)
        _show("is_active", provider.is_active)
        _show("verification_status", provider.verification_status)
        _show("pk", provider.pk)

        self.assertFalse(provider.is_active)
        self.assertEqual(
            provider.verification_status, ProviderVerificationStatus.PENDING
        )
        _ok("Registration creates correct initial state")

    def test_inactive_provider_cannot_login(self) -> None:
        _section("1.2 – Inactive provider login attempt")
        from rest_framework.exceptions import ValidationError as DRFValidationError

        from apps.provider.serializers import ProviderLoginSerializer

        make_provider(email="inactive@test.com", active=False)
        serializer = ProviderLoginSerializer(
            data={"email": "inactive@test.com", "password": "pass1234!!"}  # noqa: S106
        )
        with self.assertRaises(DRFValidationError) as ctx:
            serializer.is_valid(raise_exception=True)

        _show("error detail", str(ctx.exception.detail))
        _ok("Inactive provider correctly blocked from logging in")

    def test_verified_provider_can_login(self) -> None:
        _section("1.3 – Verified active provider login")
        from apps.provider.serializers import ProviderLoginSerializer

        make_provider(email="verified@test.com", active=True, verified=True)
        serializer = ProviderLoginSerializer(
            data={"email": "verified@test.com", "password": "pass1234!!"}  # noqa: S106
        )
        is_valid = serializer.is_valid()
        _show("serializer.is_valid()", is_valid)
        self.assertTrue(is_valid)
        _ok("Verified provider logged in successfully")

    def test_earnings_and_withdrawal(self) -> None:
        _section("1.4 – Earnings & withdrawal")
        p = make_provider(active=True, verified=True)

        _step("Adding 500 EGP …")
        p.add_earnings(Decimal("500.00"))
        p.refresh_from_db()
        _show("total_earnings", p.total_earnings)
        _show("available_balance", p.available_balance)
        self.assertEqual(p.total_earnings, Decimal("500.00"))
        self.assertEqual(p.available_balance, Decimal("500.00"))

        _step("Withdrawing 200 EGP …")
        result = p.withdraw_balance(Decimal("200.00"))
        p.refresh_from_db()
        _show("withdraw result", result)
        _show("available_balance after withdraw", p.available_balance)
        self.assertTrue(result)
        self.assertEqual(p.available_balance, Decimal("300.00"))

        _step("Over-withdraw (should fail) …")
        result = p.withdraw_balance(Decimal("1000.00"))
        _show("over-withdraw result", result)
        self.assertFalse(result)
        _ok("Earnings / withdrawal logic correct")

    def test_update_rating(self) -> None:
        _section("1.5 – update_rating rolling average")
        p = make_provider(active=True, verified=True)

        for rating in [5, 3, 4]:
            p.update_rating(rating)
            p.refresh_from_db()
            _show(f"after rating {rating} — average", float(p.average_rating))

        self.assertAlmostEqual(
            float(p.average_rating), round((5 + 3 + 4) / 3, 2), places=2
        )
        self.assertEqual(p.total_reviews, 3)
        _ok("Rolling average rating correct")

    def test_completion_rate(self) -> None:
        _section("1.6 – get_completion_rate")
        p = make_provider(active=True, verified=True)
        _show("rate with 0 jobs", p.get_completion_rate())
        self.assertEqual(p.get_completion_rate(), 0)

        p.total_jobs = 10
        p.completed_jobs = 7
        p.save(update_fields=["total_jobs", "completed_jobs"])
        _show("rate with 7/10", p.get_completion_rate())
        self.assertEqual(p.get_completion_rate(), 70.0)
        _ok("Completion rate correct")


# ═════════════════════════════════════════════════════════════════════════════
# 2.  ProviderOnboarding Model Tests
# ═════════════════════════════════════════════════════════════════════════════


class ProviderOnboardingModelTests(TestCase):
    def setUp(self) -> None:
        self.region = make_region()
        self.category = make_category()
        self.staff = make_staff()

    def test_initial_state_is_pending(self) -> None:
        _section("2.1 – New onboarding starts PENDING")
        from apps.provider.choices import OnboardingStatus

        app = make_onboarding(self.region, self.category)
        _show("status", app.status)
        _show("provider_id", app.provider_id)
        _show("applicant_id", app.applicant_id)

        self.assertEqual(app.status, OnboardingStatus.PENDING)
        self.assertIsNone(app.provider_id)
        _ok("Initial onboarding state correct")

    def test_fsm_guards_pending(self) -> None:
        _section("2.2 – FSM guards from PENDING state")
        app = make_onboarding(self.region, self.category)

        _show("can_review()", app.can_review())
        _show("can_approve()", app.can_approve())
        _show("can_reject()", app.can_reject())
        _show("can_request_changes()", app.can_request_changes())

        self.assertTrue(app.can_review())
        self.assertFalse(app.can_approve())
        self.assertFalse(app.can_reject())
        self.assertFalse(app.can_request_changes())
        _ok("PENDING guards correct")

    def test_fsm_guards_under_review(self) -> None:
        _section("2.3 – FSM guards from UNDER_REVIEW state")
        app = make_onboarding(self.region, self.category)
        app.move_to_review(self.staff)
        app.refresh_from_db()

        _show("status", app.status)
        _show("can_review()", app.can_review())
        _show("can_approve()", app.can_approve())
        _show("can_reject()", app.can_reject())
        _show("can_request_changes()", app.can_request_changes())

        self.assertFalse(app.can_review())
        self.assertTrue(app.can_approve())
        self.assertTrue(app.can_reject())
        self.assertTrue(app.can_request_changes())
        _ok("UNDER_REVIEW guards correct")

    def test_move_to_review_sets_reviewer_and_timestamp(self) -> None:
        _section("2.4 – move_to_review sets reviewer + reviewed_at")
        from apps.provider.choices import OnboardingStatus

        app = make_onboarding(self.region, self.category)
        before = timezone.now()
        app.move_to_review(self.staff)
        app.refresh_from_db()

        _show("status", app.status)
        _show("reviewed_by", app.reviewed_by)
        _show("reviewed_at", app.reviewed_at)

        self.assertEqual(app.status, OnboardingStatus.UNDER_REVIEW)
        self.assertEqual(app.reviewed_by, self.staff)
        self.assertIsNotNone(app.reviewed_at)
        self.assertGreaterEqual(app.reviewed_at, before)
        _ok("move_to_review sets correct fields")

    def test_move_to_review_from_wrong_state_raises(self) -> None:
        _section("2.5 – move_to_review from UNDER_REVIEW raises ValueError")
        app = make_onboarding(self.region, self.category)
        app.move_to_review(self.staff)

        with self.assertRaises(ValueError) as ctx:
            app.move_to_review(self.staff)

        _show("error", str(ctx.exception))
        _ok("Correctly raises ValueError for invalid FSM transition")

    def test_approve_walkin_creates_provider(self) -> None:
        _section("2.6 – approve() walk-in path creates new Provider")
        from apps.provider.choices import OnboardingStatus, ProviderVerificationStatus

        app = make_onboarding(self.region, self.category)
        app.move_to_review(self.staff)
        app.refresh_from_db()

        provider = app.approve(self.staff, password="secure123!!")  # noqa: S106
        app.refresh_from_db()

        _show("app.status", app.status)
        _show("app.provider_id", app.provider_id)
        _show("provider.is_active", provider.is_active)
        _show("provider.verification_status", provider.verification_status)
        _show("provider.is_verified", provider.is_verified)

        self.assertEqual(app.status, OnboardingStatus.APPROVED)
        self.assertIsNotNone(app.provider_id)
        self.assertTrue(provider.is_active)
        self.assertTrue(provider.is_verified)
        self.assertEqual(
            provider.verification_status, ProviderVerificationStatus.VERIFIED
        )
        self.assertEqual(provider.email, app.email)
        self.assertIn(self.category, provider.categories.all())
        _ok("Walk-in approval creates correct Provider account")

    def test_approve_walkin_without_password_raises(self) -> None:
        _section("2.7 – approve() walk-in without password raises ValueError")
        app = make_onboarding(self.region, self.category)
        app.move_to_review(self.staff)
        app.refresh_from_db()

        with self.assertRaises(ValueError) as ctx:
            app.approve(self.staff, password=None)

        _show("error", str(ctx.exception))
        _ok("Correctly raises ValueError when password missing for walk-in")

    def test_approve_preregistered_activates_existing_provider(self) -> None:
        _section("2.8 – approve() pre-registered path activates existing Provider")
        from apps.provider.choices import OnboardingStatus, ProviderVerificationStatus

        existing = make_provider(email="prereg@test.com", active=False, verified=False)
        app = make_onboarding(self.region, self.category, applicant=existing)
        app.move_to_review(self.staff)
        app.refresh_from_db()

        provider = app.approve(self.staff)
        app.refresh_from_db()
        existing.refresh_from_db()

        _show("app.status", app.status)
        _show("provider.pk == existing.pk", provider.pk == existing.pk)
        _show("existing.is_active", existing.is_active)
        _show("existing.verification_status", existing.verification_status)

        self.assertEqual(app.status, OnboardingStatus.APPROVED)
        self.assertEqual(provider.pk, existing.pk)
        self.assertTrue(existing.is_active)
        self.assertEqual(
            existing.verification_status, ProviderVerificationStatus.VERIFIED
        )
        _ok("Pre-registered provider correctly activated")

    def test_approve_preregistered_does_not_create_duplicate(self) -> None:
        _section("2.9 – approve() pre-registered does NOT create a new User row")
        user_model = get_user_model()

        existing = make_provider(email="nodup@test.com", active=False, verified=False)
        count_before = user_model.objects.filter(email="nodup@test.com").count()
        _show("users before approve", count_before)

        app = make_onboarding(self.region, self.category, applicant=existing)
        app.move_to_review(self.staff)
        app.refresh_from_db()
        app.approve(self.staff)

        count_after = user_model.objects.filter(email="nodup@test.com").count()
        _show("users after approve", count_after)
        self.assertEqual(count_before, count_after)
        _ok("No duplicate user created on pre-registered approval")

    def test_reject_sets_correct_fields(self) -> None:
        _section("2.10 – reject() sets correct fields")
        from apps.provider.choices import OnboardingStatus

        app = make_onboarding(self.region, self.category)
        app.move_to_review(self.staff)
        app.refresh_from_db()
        app.reject(self.staff, reason="Incomplete NID documents.")
        app.refresh_from_db()

        _show("status", app.status)
        _show("rejection_reason", app.rejection_reason)
        _show("rejected_at", app.rejected_at)
        _show("reviewed_by", app.reviewed_by)

        self.assertEqual(app.status, OnboardingStatus.REJECTED)
        self.assertEqual(app.rejection_reason, "Incomplete NID documents.")
        self.assertIsNotNone(app.rejected_at)
        _ok("reject() sets correct fields")

    def test_reject_from_wrong_state_raises(self) -> None:
        _section("2.11 – reject() from PENDING raises ValueError")
        app = make_onboarding(self.region, self.category)

        with self.assertRaises(ValueError) as ctx:
            app.reject(self.staff, reason="Bad docs")

        _show("error", str(ctx.exception))
        _ok("reject() from wrong state correctly raises")

    def test_request_changes_sets_correct_fields(self) -> None:
        _section("2.12 – request_changes() sets correct fields")
        from apps.provider.choices import OnboardingStatus

        app = make_onboarding(self.region, self.category)
        app.move_to_review(self.staff)
        app.refresh_from_db()
        app.request_changes(
            self.staff, change_requests="Please upload clearer NID photos."
        )
        app.refresh_from_db()

        _show("status", app.status)
        _show("change_requests", app.change_requests)
        _show("reviewed_at", app.reviewed_at)

        self.assertEqual(app.status, OnboardingStatus.CHANGES_REQUIRED)
        self.assertEqual(app.change_requests, "Please upload clearer NID photos.")
        self.assertIsNotNone(app.reviewed_at)
        _ok("request_changes() sets correct fields")

    def test_changes_required_can_move_back_to_review(self) -> None:
        _section("2.13 – CHANGES_REQUIRED → UNDER_REVIEW re-review cycle")
        from apps.provider.choices import OnboardingStatus

        app = make_onboarding(self.region, self.category)
        app.move_to_review(self.staff)
        app.refresh_from_db()
        app.request_changes(self.staff, change_requests="Need updated docs")
        app.refresh_from_db()

        self.assertTrue(app.can_review())
        app.move_to_review(self.staff)
        app.refresh_from_db()

        _show("status after re-review", app.status)
        self.assertEqual(app.status, OnboardingStatus.UNDER_REVIEW)
        _ok("Changes required → re-review cycle works correctly")

    def test_approved_application_is_terminal(self) -> None:
        _section("2.14 – APPROVED application cannot be transitioned further")
        app = make_onboarding(self.region, self.category)
        app.move_to_review(self.staff)
        app.refresh_from_db()
        app.approve(self.staff, password="secure123!!")  # noqa: S106
        app.refresh_from_db()

        self.assertFalse(app.can_review())
        self.assertFalse(app.can_approve())
        self.assertFalse(app.can_reject())

        with self.assertRaises(ValueError):
            app.move_to_review(self.staff)

        _ok("Approved application is terminal — cannot be transitioned")

    def test_rejected_application_is_terminal(self) -> None:
        _section("2.15 – REJECTED application cannot be transitioned further")
        app = make_onboarding(self.region, self.category)
        app.move_to_review(self.staff)
        app.refresh_from_db()
        app.reject(self.staff, reason="Bad actor")
        app.refresh_from_db()

        self.assertFalse(app.can_review())
        self.assertFalse(app.can_approve())
        self.assertFalse(app.can_reject())
        _ok("Rejected application is terminal — cannot be transitioned")

    def test_underage_applicant_fails_validation(self) -> None:
        _section("2.16 – Underage applicant fails clean()")
        from apps.provider.models import ProviderOnboarding

        dob = date.today() - timedelta(days=365 * 17)
        app = ProviderOnboarding(
            first_name="Young",
            last_name="Person",
            email=f"young_{uuid.uuid4().hex[:6]}@test.com",
            phone="01012345678",
            date_of_birth=dob,
            address="Cairo",
            region=self.region,
            category=self.category,
            hourly_rate=Decimal("100.00"),
            nid_front=small_image(),
            nid_back=small_image(),
            police_clearance_certificate=small_image(),
        )
        _step(f"Applicant age: {app.age}")
        with self.assertRaises(ValidationError) as ctx:
            app.full_clean()

        _show("validation error", str(ctx.exception))
        _ok("Under-18 applicant correctly rejected")

    def test_manager_queryset_methods(self) -> None:
        _section("2.17 – ProviderOnboardingManager queryset methods")
        from apps.provider.models import ProviderOnboarding

        app_pending = make_onboarding(self.region, self.category)

        app_review = make_onboarding(self.region, self.category)
        app_review.move_to_review(self.staff)

        app_approved = make_onboarding(self.region, self.category)
        app_approved.move_to_review(self.staff)
        app_approved.approve(self.staff, password="pass1234!!")  # noqa: S106

        app_rejected = make_onboarding(self.region, self.category)
        app_rejected.move_to_review(self.staff)
        app_rejected.reject(self.staff, reason="test")

        _show("pending count", ProviderOnboarding.objects.pending().count())
        _show("under_review count", ProviderOnboarding.objects.under_review().count())
        _show("approved count", ProviderOnboarding.objects.approved().count())
        _show("rejected count", ProviderOnboarding.objects.rejected().count())

        self.assertIn(app_pending, ProviderOnboarding.objects.pending())
        self.assertIn(app_review, ProviderOnboarding.objects.under_review())
        self.assertIn(app_approved, ProviderOnboarding.objects.approved())
        self.assertIn(app_rejected, ProviderOnboarding.objects.rejected())
        _ok("All manager querysets return correct results")


# ═════════════════════════════════════════════════════════════════════════════
# 3.  Admin Form Tests
# ═════════════════════════════════════════════════════════════════════════════


class ProviderOnboardingAdminFormTests(TestCase):
    def setUp(self) -> None:
        self.region = make_region()
        self.category = make_category()
        self.staff = make_staff()

    def _form_data(self, status: str, extra: dict | None = None) -> dict:
        dob = date.today() - timedelta(days=365 * 25)
        data: dict = {
            "first_name": "Test",
            "last_name": "Provider",
            "email": f"form_{uuid.uuid4().hex[:6]}@test.com",
            "phone": "01012345678",
            "date_of_birth": dob.isoformat(),
            "address": "123 Test St",
            "region": str(self.region.pk),
            "category": str(self.category.pk),
            "hourly_rate": "150.00",
            "years_of_experience": "3",
            "bio": "Test bio",
            "status": status,
            "admin_notes": "",
            "rejection_reason": "",
            "change_requests": "",
            "set_password": "",
            "confirm_password": "",
        }
        if extra:
            data.update(extra)
        return data

    def _files(self) -> dict:
        return {
            "nid_front": small_image(),
            "nid_back": small_image(),
            "police_clearance_certificate": small_image(),
        }

    def test_form_valid_for_pending_status(self) -> None:
        _section("3.1 – Form valid with PENDING status")
        from apps.provider.admin import ProviderOnboardingAdminForm
        from apps.provider.choices import OnboardingStatus

        form = ProviderOnboardingAdminForm(
            data=self._form_data(OnboardingStatus.PENDING),
            files=self._files(),
        )
        is_valid = form.is_valid()
        _show("form.is_valid()", is_valid)
        if not is_valid:
            _show("errors", form.errors)
        self.assertTrue(is_valid)
        _ok("Form valid for PENDING status")

    def test_form_requires_password_for_walkin_approval(self) -> None:
        _section("3.2 – Form requires password for walk-in approval")
        from apps.provider.admin import ProviderOnboardingAdminForm
        from apps.provider.choices import OnboardingStatus

        app = make_onboarding(self.region, self.category)
        app.move_to_review(self.staff)
        app.refresh_from_db()

        form = ProviderOnboardingAdminForm(
            data=self._form_data(OnboardingStatus.APPROVED, {"email": app.email}),
            instance=app,
            files=self._files(),
        )
        is_valid = form.is_valid()
        _show("form.is_valid()", is_valid)
        _show("non_field_errors", form.non_field_errors())
        self.assertFalse(is_valid)
        _ok("Form correctly requires password for walk-in approval")

    def test_form_password_mismatch_rejected(self) -> None:
        _section("3.3 – Password mismatch rejected by form")
        from apps.provider.admin import ProviderOnboardingAdminForm
        from apps.provider.choices import OnboardingStatus

        app = make_onboarding(self.region, self.category)
        app.move_to_review(self.staff)
        app.refresh_from_db()

        form = ProviderOnboardingAdminForm(
            data=self._form_data(
                OnboardingStatus.APPROVED,
                {
                    "email": app.email,
                    "set_password": "secure1234!!",
                    "confirm_password": "different_password",
                },
            ),
            instance=app,
            files=self._files(),
        )
        _show("form.is_valid()", form.is_valid())
        _show("non_field_errors", form.non_field_errors())
        self.assertFalse(form.is_valid())
        _ok("Password mismatch correctly rejected")

    def test_form_short_password_rejected(self) -> None:
        _section("3.4 – Password < 8 chars rejected")
        from apps.provider.admin import ProviderOnboardingAdminForm
        from apps.provider.choices import OnboardingStatus

        app = make_onboarding(self.region, self.category)
        app.move_to_review(self.staff)
        app.refresh_from_db()

        form = ProviderOnboardingAdminForm(
            data=self._form_data(
                OnboardingStatus.APPROVED,
                {"email": app.email, "set_password": "abc", "confirm_password": "abc"},
            ),
            instance=app,
            files=self._files(),
        )
        self.assertFalse(form.is_valid())
        _ok("Short password correctly rejected")

    def test_form_no_password_needed_for_preregistered(self) -> None:
        _section("3.5 – No password needed when approving pre-registered provider")
        from apps.provider.admin import ProviderOnboardingAdminForm
        from apps.provider.choices import OnboardingStatus

        existing = make_provider(email="preform@test.com", active=False)
        app = make_onboarding(
            self.region, self.category, applicant=existing, email=existing.email
        )
        app.move_to_review(self.staff)
        app.refresh_from_db()

        _step("Submitting approval form for pre-registered WITHOUT password …")
        form = ProviderOnboardingAdminForm(
            data=self._form_data(
                OnboardingStatus.APPROVED,
                {"email": existing.email, "applicant": str(existing.pk)},
            ),
            instance=app,
            files=self._files(),
        )
        is_valid = form.is_valid()
        _show("form.is_valid()", is_valid)
        if not is_valid:
            _show("errors", form.errors)
            _show("non_field_errors", form.non_field_errors())
        self.assertTrue(is_valid)
        _ok("Pre-registered approval correctly skips password requirement")


# ═════════════════════════════════════════════════════════════════════════════
# 4.  Edge-Case Tests
# ═════════════════════════════════════════════════════════════════════════════


class OnboardingEdgeCaseTests(TestCase):
    def setUp(self) -> None:
        self.region = make_region()
        self.category = make_category()
        self.staff = make_staff()

    def test_double_approve_raises(self) -> None:
        _section("4.1 – Double approve() raises ValueError")
        app = make_onboarding(self.region, self.category)
        app.move_to_review(self.staff)
        app.refresh_from_db()
        app.approve(self.staff, password="first_pass!!")  # noqa: S106
        app.refresh_from_db()

        with self.assertRaises(ValueError) as ctx:
            app.approve(self.staff, password="second_pass!!")  # noqa: S106

        _show("error", str(ctx.exception))
        _ok("Double-approve correctly raises ValueError")

    def test_full_happy_path_preregistered(self) -> None:
        _section("4.2 – Full happy path: API register → office → approve → login")
        from apps.provider.choices import OnboardingStatus, ProviderVerificationStatus
        from apps.provider.serializers import ProviderLoginSerializer

        _step("Step 1: Provider registers via API …")
        provider = make_provider(
            email="happypath@test.com", active=False, verified=False
        )
        _show("  is_active", provider.is_active)
        _show("  verification_status", provider.verification_status)

        _step("Step 2: Staff creates onboarding application …")
        app = make_onboarding(
            self.region, self.category, applicant=provider, email=provider.email
        )
        _show("  app.status", app.status)

        _step("Step 3: Admin moves to Under Review …")
        app.move_to_review(self.staff)
        app.refresh_from_db()
        _show("  app.status", app.status)

        _step("Step 4: Admin approves …")
        app.approve(self.staff)
        app.refresh_from_db()
        provider.refresh_from_db()
        _show("  app.status", app.status)
        _show("  provider.is_active", provider.is_active)
        _show("  provider.verification_status", provider.verification_status)

        _step("Step 5: Provider logs in …")
        serializer = ProviderLoginSerializer(
            data={"email": "happypath@test.com", "password": "pass1234!!"}  # noqa: S106
        )
        is_valid = serializer.is_valid()
        _show("  login valid", is_valid)

        self.assertEqual(app.status, OnboardingStatus.APPROVED)
        self.assertTrue(provider.is_active)
        self.assertEqual(
            provider.verification_status, ProviderVerificationStatus.VERIFIED
        )
        self.assertTrue(is_valid)
        _ok("Full happy path completed successfully!")

    def test_full_happy_path_walkin(self) -> None:
        _section("4.3 – Full happy path: walk-in (no prior registration)")
        from apps.provider.choices import OnboardingStatus, ProviderVerificationStatus

        _step("Step 1: Staff creates walk-in onboarding …")
        app = make_onboarding(self.region, self.category)
        _show("  app.email", app.email)
        _show("  app.applicant_id", app.applicant_id)

        _step("Step 2: Admin moves to Under Review …")
        app.move_to_review(self.staff)
        app.refresh_from_db()

        _step("Step 3: Admin approves with password …")
        provider = app.approve(self.staff, password="walkin_secure!!")  # noqa: S106
        app.refresh_from_db()

        _show("  app.status", app.status)
        _show("  provider.email", provider.email)
        _show("  provider.is_active", provider.is_active)
        _show("  provider.verification_status", provider.verification_status)

        self.assertEqual(app.status, OnboardingStatus.APPROVED)
        self.assertTrue(provider.is_active)
        self.assertEqual(
            provider.verification_status, ProviderVerificationStatus.VERIFIED
        )
        _ok("Walk-in happy path completed successfully!")

    def test_changes_required_then_approved(self) -> None:
        _section("4.4 – Changes required → re-review → approve cycle")
        from apps.provider.choices import OnboardingStatus

        app = make_onboarding(self.region, self.category)
        app.move_to_review(self.staff)
        app.refresh_from_db()

        _step("Admin requests changes …")
        app.request_changes(self.staff, change_requests="Provide clearer ID photo")
        app.refresh_from_db()
        _show("  status after changes_required", app.status)

        _step("Provider updates docs, staff re-reviews …")
        app.move_to_review(self.staff)
        app.refresh_from_db()
        _show("  status after re-review", app.status)

        _step("Admin approves …")
        app.approve(self.staff, password="final_pass!!")  # noqa: S106
        app.refresh_from_db()
        _show("  status after approval", app.status)

        self.assertEqual(app.status, OnboardingStatus.APPROVED)
        _ok("Changes-required cycle completed and approved successfully!")
