# Generated by Django 6.0.1 on 2026-02-03 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Current wallet balance', max_digits=10)),
                ('total_cashback', models.DecimalField(decimal_places=2, default=0.0, help_text='Total cashback earned', max_digits=10)),
                ('total_bookings', models.IntegerField(default=0, help_text='Total number of bookings made')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
            },
            bases=('user.user',),
        ),
    ]
