# Generated by Django 6.0.1 on 2026-02-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='favorite_providers',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='provider.provider'),
        ),
    ]
