name: CI

on:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    services:
      postgres:
        image: postgis/postgis:17-3.5-alpine
        env:
          POSTGRES_DB: snapfix
          POSTGRES_USER: snapfix
          POSTGRES_PASSWORD: snapfix123
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DEBUG: "True"
      ALLOWED_HOSTS: "localhost,127.0.0.1"
      DB_NAME: snapfix
      DB_USER: snapfix
      DB_PASSWORD: snapfix123
      DB_HOST: localhost
      DB_PORT: "5432"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Install GIS dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            binutils \
            libproj-dev \
            gdal-bin \
            libgdal-dev

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint with Ruff
        run: ruff check . --output-format=github

      - name: Check formatting
        run: ruff format --check .

      #- name: Security scan (Bandit)
      #run: bandit -r .

      - name: Check for missing migrations
        run: python manage.py makemigrations --check --dry-run

      - name: Apply migrations
        run: python manage.py migrate

      - name: Run tests
        run: python manage.py test
