# Generated by Django 6.0.1 on 2026-04-11 13:06

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("request_assigned", "Request Assigned"),
                            ("quote_received", "Quote Received"),
                            ("request_accepted", "Request Accepted"),
                            ("job_started", "Job Started"),
                            ("job_completed", "Job Completed"),
                            ("request_declined", "Request Declined"),
                            ("cancelled_by_provider", "Cancelled by Provider"),
                            ("quote_approved", "Quote Approved"),
                            ("quote_rejected", "Quote Rejected"),
                            ("cancelled_by_customer", "Cancelled by Customer"),
                            ("payment_settled", "Payment Settled"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("data", models.JSONField(default=dict)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "-created_at"],
                        name="notif_recipient_created_idx",
                    ),
                    models.Index(
                        fields=["recipient", "is_read"], name="notif_recipient_read_idx"
                    ),
                ],
            },
        ),
    ]
